### ISSUE TITLE
STklos tests crash on some big-endian machines

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#11]
This is a separate issue from #10 so I opened this new one.

I have ran the STklos tests on some machines:

```
machine		end	mem	stklos-compile	test results
qemu arm	L	256	fail		OK
qemu malta be	B	256	fail		segf call/cc
			128	fail		segf call/cc
qemu malta le	L	256	fail		OK
Archer c7v4	B	128+64	fail		segf call/cc
DIR-505		B	64	fail		segf call/cc,circular (*)
Asus RT-AC51U	L	64+32	fail		OK
			64	fail		OK
x86_64		L	huge	OK		OK
```

(*) I don't know why this one segfaults the circular structures test.
    It is an old router, running with the root filesystem on a pendrive,
    and low on memory. Maybe it had not enough memory to finish.

Memory is in Mb.
"malta" is emulated MIPS.
In the memory column, "128+64" means "128Mb RAM plus 64 swap-on-compressed-ram". Tested with different amounts of memory to see if it made a difference in the call/cc test
I wanted to test the qemu MIPS be version with 64Mb, but it's not enough for it to boot.

On little-endian machines, all runs well. On big-endian ones,
```
# stklos --no-init-file --utf8-encoding=yes -f do-test.stk
==== Testing Numbers  ...                                        passed
==== Testing Keywords  ...                                       passed
==== Testing call/cc & dynamic-wind  ...                         Segmentation fault
```
If I comment out the call/cc tests, the rest runs fine.

The test logs end like this:
```
==== Testing call/cc & dynamic-wind  ==================================
call/cc =========================================================
  testing foo.1 expects 1200 ==> OK.
  testing foo.1 expects 120 ==> OK.
  testing Al Petrofsky, 15 June 2002 expects 1 ==> OK.
```
So it seems that the test that failed is the one right after Al Petrofsky.

I have ran gdb, it seems to happen when cloning an environment:

```
# gdb stklos
...
(gdb) run --no-init-file --utf8-encoding=yes -f do-test.stk
Starting program: /usr/bin/stklos --no-init-file --utf8-encoding=yes -f do-test.stk
warning: Unable to find dynamic linker breakpoint function.
GDB will be unable to debug shared library initializers
and track explicitly loaded dynamic code.
==== Testing Numbers  ...                                        passed
==== Testing Keywords  ...                                       passed
==== Testing call/cc & dynamic-wind  ...                         
Program received signal SIGSEGV, Segmentation fault.
0x00426c83 in clone_env (e=0x1b0004, vm=0x77da3f78) at vm.c:345
345	vm.c: No such file or directory.
(gdb) where
#0  0x00426c83 in clone_env (e=0x1b0004, vm=0x77da3f78) at vm.c:345
#1  0x00426d9b in patch_environment (vm=0x77da3f78) at vm.c:382
#2  STk_make_continuation () at vm.c:1967
#3  0x004294cd in run_vm (vm=vm@entry=0x77da3f78) at vm.c:1787
#4  0x004298f7 in STk_C_apply (func=func@entry=0x77c9d5f0, nargs=<optimized out>, nargs@entry=0) at vm.c:530
#5  0x00429941 in STk_call_with_values (prod=<optimized out>, con=0x77c9d528) at vm.c:649
#6  0x004295c7 in run_vm (vm=vm@entry=0x77da3f78) at vm.c:1823
#7  0x0042978f in STk_execute (code=<optimized out>, consts=<optimized out>, envt=0x77d98fa0) at vm.c:577
#8  0x00429535 in run_vm (vm=vm@entry=0x77da3f78) at vm.c:1820
#9  0x004298f7 in STk_C_apply (func=func@entry=0x77c9dca8, nargs=<optimized out>, nargs@entry=0) at vm.c:530
#10 0x00429941 in STk_call_with_values (prod=<optimized out>, con=0x77c9dc08) at vm.c:649
#11 0x004295c7 in run_vm (vm=vm@entry=0x77da3f78) at vm.c:1823
#12 0x004298f7 in STk_C_apply (func=<optimized out>, nargs=<optimized out>, nargs@entry=1) at vm.c:530
#13 0x00414587 in STk_load_source_file (f=f@entry=0x77d845a0) at fport.c:787
#14 0x004145cd in load_file (filename=filename@entry=0x77baef60) at fport.c:806
#15 0x00414639 in STk_scheme_try_load (filename=0x77baef60) at fport.c:853
#16 0x004294fd in run_vm (vm=vm@entry=0x77da3f78) at vm.c:1790
#17 0x00429cbd in STk_boot_from_C () at vm.c:2218
#18 0x0041065d in main (argc=<optimized out>, argv=<optimized out>) at stklos.c:213
warning: GDB can't find the start of the function at 0x77f70f2b.

    GDB is unable to find the start of the function at 0x77f70f2b
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0x77f70f2b for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
```

I see that in `vm.c` there are some uses of `>>` and `& 0xff`, in the definition of `FIRST_BYTE` and `SECOND_BYTE`, but those don't seem to make a difference (I suppose).

I also tried valgrind, but it didn't help:

```
valgrind  stklos --no-init-file --utf8-encoding=yes -f do-test.stk
==18334== Memcheck, a memory error detector
==18334== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==18334== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==18334== Command: stklos --no-init-file --utf8-encoding=yes -f do-test.stk
==18334== 
==18334== Conditional jump or move depends on uninitialised value(s)
==18334==    at 0x4074504: ??? (in /lib/libc.so)
==18334==    by 0x408594C: ??? (in /lib/libc.so)
==18334== 
==18334== Conditional jump or move depends on uninitialised value(s)
==18334==    at 0x4073970: ??? (in /lib/libc.so)
==18334==    by 0x4073F38: ??? (in /lib/libc.so)
==18334== 
vex mips->IR: unhandled instruction bytes: 0x40 0x1A 0x0 0x5C

vex: priv/guest_mips_toIR.c:1304 (jmp_lit32): Assertion `dres->whatNext == Dis_Continue' failed.
vex storage: T total 34819232 bytes allocated
vex storage: P total 0 bytes allocated

valgrind: the 'impossible' happened:
   LibVEX called failure_exit().

host stacktrace:
==18334==    at 0x5803DB88: ??? (in /usr/lib/valgrind/memcheck-mips32-linux)
==18334==    by 0x5803DB74: ??? (in /usr/lib/valgrind/memcheck-mips32-linux)

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 18334)
==18334==    at 0x410301: main (stklos.c:168)
client stack range: [0x7E87F000 0x7E87FFFF] client SP: 0x7E87FCA8
valgrind stack range: [0x426F8000 0x427F7FFF] top usage: 5552 of 1048576
```

**Comment by jpellegrini** [comment]
I've made a little progress here.

before I show what I found, I'll add some more specific instructions to reproduce the gdb output I got:

- use a router with extroot, or a qemu virtual machine, in order to be able to install gdb
- compile the stklos OpenWRT package, install on the router, using gcc-10 with `CFLAGS="-g -O0 -fanalyzer"`
- for some reason, even though I compiled with `-g -O0`, the binary on the router had no debug information. I had to `scp stklos root@router:`, and then, on the router, `mv stklos /usr/bin`.
- create a directory `/root/tests/` on the router, and copy stklos tests (and maybe the C sources) into the router, in that directory
- install gdb on the router (`opkg install gdb`)
- run `gdb stklos` as shown in my initial report



So -- this is what I found:

- I noticed that in different runs of the above debugging procedure, the values of `e` and `vm` are the same (`0x1b0004` and `0x77da3f78`).
- I have changed the line `if (FRAMEP(e) && IS_IN_STACKP(e)) {` to
```
  if (FRAMEP(e))
      if (IS_IN_STACKP(e)) {
```
and it seems to segfault in `FRAMEP(e)`, because if I change the order of the `if`s,
```
 if (IS_IN_STACKP(e))
    if (FRAMEP(e))
```
then it segfaults in *another* function, `verif_environment`, in a line where there is... Another `FRAMEP(e)`:
```
==== Testing call/cc & dynamic-wind  ...
Program received signal SIGSEGV, Segmentation fault.
0x0043485d in verif_environment (vm=0x77da3f78) at vm.c:364
364	    for (env = ACT_SAVE_ENV(lfp); FRAMEP(env); env = FRAME_NEXT(env)){
(gdb) where
#0  0x0043485d in verif_environment (vm=0x77da3f78) at vm.c:364
#1  0x004348bf in patch_environment (vm=0x77da3f78) at vm.c:387
```

A relevant point: using gcc-10 and its static aanalysis tool (with `-fanalyzer`), I got some warnings from gcc about `BOXED_TYPE_EQ`, which is used in the definition of `FRAMEP`.

```
str.c: In function ‘control_index’:
stklos.h:215:52: warning: dereference of NULL ‘s’ [CWE-690] [-Wanalyzer-null-dereference]
  215 | #define BOXED_TYPE(x)           (((stk_header *) x)->type)
      |                                 ~~~~~~~~~~~~~~~~~~~^~~~~~~
stklos.h:218:51: note: in expansion of macro ‘BOXED_TYPE’
  218 | #define BOXED_TYPE_EQ(x, y)     (BOXED_OBJP(x) && BOXED_TYPE(x) == y)
      |                                                   ^~~~~~~~~~
stklos.h:1186:27: note: in expansion of macro ‘BOXED_TYPE_EQ’
 1186 | #define STRINGP(p)       (BOXED_TYPE_EQ((p), tc_string))
      |                           ^~~~~~~~~~~~~
str.c:174:8: note: in expansion of macro ‘STRINGP’
  174 |   if (!STRINGP(s)) error_bad_string(s);
      |        ^~~~~~~
  ‘STk_string2utf8’: event 1
    |
    |stklos.h:273:18:
    |  273 |   SCM CPP_CONCAT(STk_, _cname) _params
    |      |                  ^~~~
    |      |                  |
    |      |                  (1) entry to ‘STk_string2utf8’
stklos.h:92:33: note: in definition of macro ‘CPP_CONCAT’
    |   92 | #define CPP_CONCAT(x, y)        x##y
    |      |                                 ^
str.c:1315:1: note: in expansion of macro ‘DEFINE_PRIMITIVE’
    | 1315 | DEFINE_PRIMITIVE("string->utf8", string2utf8, vsubr, (int argc, SCM *argv))
    |      | ^~~~~~~~~~~~~~~~
    |
  ‘STk_string2utf8’: event 2
    |
    | 1322 |   str           = control_index(argc, argv, &start, &end);
    |      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                   |
    |      |                   (2) calling ‘control_index’ from ‘STk_string2utf8’
    |
    +--> ‘control_index’: events 3-7
           |
           |  159 | static SCM control_index(int argc, SCM *argv, long *pstart, long *pend)
           |      |            ^~~~~~~~~~~~~
           |      |            |
           |      |            (3) entry to ‘control_index’
           |  160 | {
           |  161 |   SCM s = NULL;
           |      |       ~
           |      |       |
           |      |       (4) ‘s’ is NULL
           |......
           |  165 |   switch (argc) {
           |      |   ~~~~~~
           |      |   |
           |      |   (5) following ‘default:’ branch...
           |......
           |  170 |   default: STk_error("incorrect number of arguments (%d)", argc);
           |      |   ~~~~~~~
           |      |   |
           |      |   (6) ...to here
           |......
           |  174 |   if (!STRINGP(s)) error_bad_string(s);
           |      |      ~
           |      |      |
           |      |      (7) following ‘false’ branch...
           |
         ‘control_index’: event 8
           |
           |stklos.h:215:52:
           |  215 | #define BOXED_TYPE(x)           (((stk_header *) x)->type)
           |      |                                 ~~~~~~~~~~~~~~~~~~~^~~~~~~
           |      |                                                    |
           |      |                                                    (8) ...to here
stklos.h:218:51: note: in expansion of macro ‘BOXED_TYPE’
           |  218 | #define BOXED_TYPE_EQ(x, y)     (BOXED_OBJP(x) && BOXED_TYPE(x) == y)
           |      |                                                   ^~~~~~~~~~
stklos.h:1186:27: note: in expansion of macro ‘BOXED_TYPE_EQ’
           | 1186 | #define STRINGP(p)       (BOXED_TYPE_EQ((p), tc_string))
           |      |                           ^~~~~~~~~~~~~
str.c:174:8: note: in expansion of macro ‘STRINGP’
           |  174 |   if (!STRINGP(s)) error_bad_string(s);
           |      |        ^~~~~~~
           |
         ‘control_index’: event 9
           |
           |stklos.h:215:52:
           |  215 | #define BOXED_TYPE(x)           (((stk_header *) x)->type)
           |      |                                 ~~~~~~~~~~~~~~~~~~~^~~~~~~
           |      |                                                    |
           |      |                                                    (9) dereference of NULL ‘s’
stklos.h:218:51: note: in expansion of macro ‘BOXED_TYPE’
           |  218 | #define BOXED_TYPE_EQ(x, y)     (BOXED_OBJP(x) && BOXED_TYPE(x) == y)
           |      |                                                   ^~~~~~~~~~
stklos.h:1186:27: note: in expansion of macro ‘BOXED_TYPE_EQ’
           | 1186 | #define STRINGP(p)       (BOXED_TYPE_EQ((p), tc_string))
           |      |                           ^~~~~~~~~~~~~
str.c:174:8: note: in expansion of macro ‘STRINGP’
           |  174 |   if (!STRINGP(s)) error_bad_string(s);
           |      |        ^~~~~~~
```
That was the first warning related to this which gcc issued, in `str.c` (it did not issue the same warning in `vm.c`, probably because it was already done in `str.c`).

But it does complain about `VECTORP` in a similar way (I won't reproduce this one fully here, because it's quite similar to the `FRAMEP` one):
```
vector.c: In function ‘control_index’:
stklos.h:215:52: warning: dereference of NULL ‘v’ [CWE-690] [-Wanalyzer-null-dereference]
  215 | #define BOXED_TYPE(x)           (((stk_header *) x)->type)
      |                                 ~~~~~~~~~~~~~~~~~~~^~~~~~~
stklos.h:218:51: note: in expansion of macro ‘BOXED_TYPE’
  218 | #define BOXED_TYPE_EQ(x, y)     (BOXED_OBJP(x) && BOXED_TYPE(x) == y)
      |                                                   ^~~~~~~~~~
stklos.h:1362:24: note: in expansion of macro ‘BOXED_TYPE_EQ’
 1362 | #define VECTORP(p)    (BOXED_TYPE_EQ((p), tc_vector))
      |                        ^~~~~~~~~~~~~
...
```
@egallesio  - are there functions/macros/tools specific to STkos that I may use to help debug this? I'm not that familiar with the internals of STklos.

**Comment by jpellegrini** [comment]
Didn' tthink too much about this, but... On machines with different endiannes, wouldn't this
```
#define BOXED_OBJP(x)           (!(AS_LONG(x) & 3))
```
be a problem?

**Comment by jpellegrini** [comment]
Ok. I am confused now.

I  removed the loop from `verif_environment`:

```
static void verif_environment(vm_thread_t *vm)
{
  SCM *lfp, *env;

  //STk_debug("<<<<<<VVVVVVVV<<<<");
  for (lfp = vm->fp; lfp; lfp = ACT_SAVE_FP(lfp)) {
    SCM self = (SCM) (ACT_SAVE_PROC(lfp));
    //STk_debug("self = ~S", self);
    if (!self || !ACT_SAVE_ENV(lfp)) break;

    //STk_debug("++++ %d", ACT_SAVE_ENV(lfp));
//    for (env = ACT_SAVE_ENV(lfp); FRAMEP(env); env = FRAME_NEXT(env)){
      //STk_debug("    On a l'environment ~S (%d)", (SCM) env,
      //IS_IN_STACKP(env));

//    }
    //STk_debug("---");
  }
  //STk_debug(">>>VVV>>>>>>>");
}
```

Now STklos passes all tests (!!!) on my big-endian machine.

However, running gdb on the tests fails... With `SIGPWR`  (uh???)

```
(gdb) run --no-init-file --utf8-encoding=yes -f do-test.stk
Starting program: /usr/bin/stklos --no-init-file --utf8-encoding=yes -f do-test.stk
warning: Unable to find dynamic linker breakpoint function.
GDB will be unable to debug shared library initializers
and track explicitly loaded dynamic code.
==== Testing Numbers  ...                                        passed
==== Testing Keywords  ...                                       passed
==== Testing call/cc & dynamic-wind  ...                         passed
==== Testing String Ports (SRFI 6)  ...                          passed
==== Testing File Ports  ...                                     passed
==== Testing Threads  ...                                        [New LWP 3696]
[New LWP 3697]
[LWP 3696 exited]
[New LWP 3698]

Thread 3 "stklos" received signal SIGPWR, Power fail/restart.
[Switching to LWP 3697]
0x77f618a4 in ?? ()
```

(And gdb won't find more debugging info, even though the binary does have debug_info and was not stripped -- probably, it crashed inside pthreads code...)
But it only crashes inside gdb.

**Comment by egallesio** [comment]
Hi @jpellegrini,

Just a quick response before a longer one... 
I have just restarted to have time to work on STklos and I have seen your 3 (long) messages. I've just started to read them and I need more time have to figure out all the information they contain. 

First, thank you for showing me the -fanalyzer option of gcc (didn't notice that, but it is tremendously interesting). 
To answer one of your questions, you can compile the code with the  `-DSTK_DEBUG`  cc option.  It will mainly provides you the `STk_debug` a kind of `printf` which accepts `%` and `~` formats to print C or Scheme values as in 

```
STk_debug("Value %d = ~S", 1, MAKE_INT(1));
```
Greping STK_DEBUG in the src directory will also reveal some minor debugging functions. I fear that's all we have...  

Thanks for your interest in STklos

**Comment by jpellegrini** [comment]
Ok -- I have tried, but since I am compiling against musl (not glibc), `-DSTK_DEBUG` doesn't work (because musl does not support `execinfo.h`, which seems to be necessary when using `STk_debug`.

Anyway -- about the `SIGPWR` problem, I'm not sure I can trust gdb on that.
I will try to run more tests on more big-endian machines.

**Comment by egallesio** [comment]
Global response to the messages of the 05/15 

1. I definitively must look at the result of -fanalyzer. I don't completely grab the results displayed, but having a static analysis is really cool.
2. I don't think  that the endianess of the underlying machine could be a problem since the whole value should be  grabbed as a whole form memory to a register before  doing the and operation.
3. In fact the function  `verif_environment` is not needed at all. This was a debug function and it should not be here. You can safely delete it without problem. I have done that and it is OK on my machine. About the SIGPWR signal, this is the Boehm GC which use it to stop threads (see https://www.hboehm.info/gc/debugging.html): 
_On most platforms, the multithreaded version of the collector needs one or two other signals for internal use by the collector in stopping threads. It is normally wise to tell the debugger to ignore these. On Linux, the collector currently uses SIGPWR and SIGXCPU by default._

I'm thinking that you have resolved the bug on the big-endian machines. I commit my last change. If you can test it on your routers, it would be great. Perhaps, it is finally time to close this issue ;-)

**Comment by egallesio** [comment]
> Ok -- I have tried, but since I am compiling against musl (not glibc), `-DSTK_DEBUG` doesn't work (because musl does not support `execinfo.h`, which seems to be necessary when using `STk_debug`.
> 
> Anyway -- about the `SIGPWR` problem, I'm not sure I can trust gdb on that.
> I will try to run more tests on more big-endian machines.

To be able to compile on musl, you can comment the function `%c-backtrace` which should be the only one needing `execinfo.h`.

**Comment by egallesio** [comment]
Of course, don't worry (and there is no obligation to do so of course). I didn't want to hurry up  you. 
Since, I have failed to make a really workable MIPS environment on qemu, I'm will not be able to test it myself. 
If you have time to test it would be great, but take your time (after all you seem to be the only user trying to run STklos on those weird architectures ;-)

**Comment by jpellegrini** [comment]
Ok - I have made a pull request with the fix. Basically,   the patch changes the order of tests inside the 'if', so IS_IN_STACKP(e) is checked before FRAMEP(e). That seems to fix the problem on all my machines, and on the 32-big big-endian MIPS emulator.

It is indeed a weird architecture. Big-endian is supposed to be dead, but there are wireless routers being produced using big-endian mips! (In fact, one very popular choice for OpenWRT is the TP-Link Archer C7, which is big-endian).

**Comment by jpellegrini** [comment]
@egallesio thanks for accepting the PR!
I have tested again, and everything is fine -- as far as I am concerned, this issue can be closed!
