### ISSUE TITLE
Format segmentation fault

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#203]
With no modules loaded:

```
$ stklos
  \    STklos version 1.60  (Id: 763371d)
   \   Copyright (C) 1999-2021 Erick Gallesio <eg@unice.fr>
  / \  Université Côte d'Azur
 /   \ [Linux-5.10.0-6-amd64-x86_64/pthread/readline/utf8]
stklos>  (format #t "a ~4f~%" 'a)
Received a SIGSGV signal.
Try to augment stack size (--stack-size option).
If the problem persists, send a mail to <bugs@stklos.net>
```

Output from gdb:

```
Thread 1 "stklos" received signal SIGSEGV, Segmentation fault.
0x000055555557f317 in STk_hash_get_variable ()
(gdb) where
#0  0x000055555557f317 in STk_hash_get_variable ()
#1  0x0000555555577a79 in STk_lookup ()
#2  0x00005555555a70db in ?? ()
#3  0x00005555555a58e3 in STk_C_apply ()
#4  0x00005555555918ce in ?? ()
#5  0x0000555555591c46 in STk_format ()
#6  0x00005555555ac845 in ?? ()
#7  0x00005555555a58e3 in STk_C_apply ()
#8  0x00005555555918ce in ?? ()
#9  0x0000555555591c46 in STk_format ()
#10 0x00005555555ac845 in ?? ()

...

#6763 0x00005555555a58e3 in STk_C_apply ()
#6764 0x00005555555918ce in ?? ()
#6765 0x0000555555591c46 in STk_format ()
#6766 0x00005555555ac845 in ?? ()
#6767 0x00005555555a58e3 in STk_C_apply ()
#6768 0x00005555555918ce in ?? ()
#6769 0x0000555555591c46 in STk_format ()
#6770 0x00005555555ac845 in ?? ()
#6771 0x00005555555a5c29 in STk_execute ()
#6772 0x00005555555ac7df in ?? ()
#6773 0x00005555555a58e3 in STk_C_apply ()
#6774 0x00005555555a5dcb in STk_call_with_values ()
#6775 0x00005555555ac3a1 in ?? ()
#6776 0x00005555555a58e3 in STk_C_apply ()
#6777 0x00005555555a5dcb in STk_call_with_values ()
#6778 0x00005555555ac3a1 in ?? ()
#6779 0x00005555555ad693 in STk_boot_from_C ()
#6780 0x000055555559bce5 in main ()
```

**Comment by egallesio** [comment]
Hi @jpellegrini,

 I'll look at this today (I have also a different behavior with ~f on Android, that I need to fix).

**Comment by jpellegrini** [comment]
> I have also a different behavior with ~f on Android, that I need to fix

Did you manage to compile on Android? I think the issue I described (#199 ) is related to Android 11 only.
I'll see if I  can get another device to test.

**Comment by egallesio** [comment]
This should be fixed now. 

> Did you manage to compile on Android? I think the issue I described (#199 ) is related to Android 11 only.

Not seen thin problem on an Android 10 (I don't have a  version 11 device available).

**Comment by jpellegrini** [comment]
This issue is fixed! :)
