### ISSUE TITLE
Segfault in VM

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#664]
Hi @egallesio !

Look what we have:

```scheme
(define (ack m n)
  (cond ((= m 0) (+ n 1))
        ((= n 0) (ack (- m 1) 1))
        (else (ack (- m 1) (ack m (- n 1))))))
```

Then try `(ack 12 32765)`... STklos segfaults:

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555b52aa in run_vm (vm=0x7ffff7afbf00) at vm.c:1198
1198	CASE(NOP) { NEXT; }
(gdb) where
#0  0x00005555555b52aa in run_vm (vm=0x7ffff7afbf00) at vm.c:1198
#1  0x00005555555b4ba2 in STk_execute (code=0x7ffff758fb40, consts=0x7ffff749c620, envt=0x7ffff7b11f30) at vm.c:694
#2  0x00005555555bc7b4 in run_vm (vm=0x7ffff7afbf00) at vm.c:2251
#3  0x00005555555b4818 in STk_C_apply (func=0x7ffff7499380, nargs=0) at vm.c:647
#4  0x00005555555b4d40 in STk_call_for_values (prod=0x7ffff7499380) at vm.c:752
#5  0x00005555555bc335 in run_vm (vm=0x7ffff7afbf00) at vm.c:2221
#6  0x00005555555b4818 in STk_C_apply (func=0x7ffff7499480, nargs=0) at vm.c:647
#7  0x00005555555b4d40 in STk_call_for_values (prod=0x7ffff7499480) at vm.c:752
#8  0x00005555555bc335 in run_vm (vm=0x7ffff7afbf00) at vm.c:2221
#9  0x00005555555bd80c in STk_boot_from_C () at vm.c:2677
#10 0x00005555555a9a2e in main (argc=0, argv=0x7fffffffdfe0) at stklos.c:285
```

Line 1198 of `vm.c` is
```c
CASE(NOP) { NEXT; }
```

This is confusing. Why is a `NOP` being executed, if it isn't generated? (I have checked teh disassembly of `ack`). And why does it segfault? Is `*jump_table[(fetch_next())]` zero? Why? 

```c
#    define NEXT          goto *jump_table[fetch_next()];
```

**Comment by jpellegrini** [comment]
Oh, sorry!  It seems that this is caused by the default stack size not being enough. |Closing...
